import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Manrope } from 'next/font/google'


const manrope = Manrope({
  subsets: ['latin'], 
  display: 'swap',
  weight: ['400', '500', '700'], 
  variable: '--font-manrope',

});

export const metadata: Metadata = {
  title: "travel-home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} antialiased`}
        
      >
        <Navbar />
     

        
        {children}
           <Footer/>
      </body>
    </html>
  );
}
